### ISSUE TITLE
Autop XMLRPC Content in new versions of WP

### ISSUE THREAD

**Issue by joeauty** [chrisguitarguy/WPSE-Plugins#4]
Hello Chris,

I'm wondering if this trick still works in new versions of WordPress, do you happen to know? I'm unable to get it to work, WordPress is returning blank objects with all content.

No worries if you don't have a quick answer, I'm just wondering if you've dealt with this before I dig deeper.

**Comment by chrisguitarguy** [comment]
I haven't, I would think it would still work. WordPress wouldn't have removed any filters.

Do you have `WP_DEBUG` turned on? Any errors?

**Comment by joeauty** [comment]
Sorry for my delay here, I've been swamped.. I'm seeing the following error:

{ [Error: XML-RPC fault: server error. requested method wp.getPosts does not exist.]
  code: -32601,
  faultCode: -32601,
  faultString: 'server error. requested method wp.getPosts does not exist.' }

This goes away with the plugin disabled.

**Comment by joeauty** [comment]
The getPosts method is requested by https://github.com/scottgonzalez/node-wordpress , so this might be a problem with that library and interpreting paragraphs, maybe a sanitization issue?

**Comment by chrisguitarguy** [comment]
`wp.getPosts` is not the method my plugin adds, it's a built in WordPress one. The plugin adds the [`post_autop`](https://github.com/chrisguitarguy/WPSE-Plugins/blob/3e64bd5e2594f4ef269e7e53bff55b2c6ee125c9/xmlrpc-autop.php#L32) method.

**Comment by joeauty** [comment]
I see... I think the problem is this?

function wpse44849_xmlrpc_methods($method)
{
    $methods['post_autop'] = 'wpse44849_autop_callback';
    return $methods;
}

Shouldn't it be:

function wpse44849_xmlrpc_methods($methods)
{
    $methods['post_autop'] = 'wpse44849_autop_callback';
    return $methods;
}

Is there a way to automatically apply this method to all XML RPC requests for content, or does this have to be invoked manually?

**Comment by chrisguitarguy** [comment]
Good catch, fixed!

> Is there a way to automatically apply this method to all XML RPC requests for content, or does this have to be invoked manually?

You could replace `getPosts` or inspect how [WordPress does it](https://github.com/WordPress/WordPress/blob/e199d2420fd628b8f558cabcaed79b9eb39ecaa6/wp-includes/class-wp-xmlrpc-server.php#L1617-L1691) and see if there's any filters you can use.
